mangoszero/database

- World/Updates/Rel21/21000_05_Script_refactoring.sql
This is required for the updated core, https://github.com/mangoszero/server/pull/4
Note that it changes format of the few tables.
> [SD2] Major refactoring of SD2 script system

- World/Updates/Rel21/21000_10_warden_multiversion.sql
See also core commit.
For now, the new table is filled with few overrides for 6005 client only. Warden accepts seemingly the client now.
> [Warden] Support of several client builds

- World/Updates/Rel21/21000_16_Terl_Arakor_Wetlands_gossip_text.sql
This NPC will now have a choice of things to say when interacted with.
> Terl Arakor - missing gossip text added

- World/Updates/Rel21/Rel21_1_13_dbdocs_update_item_template.sql
New subtables added, and Notes and field comments added to the
item_template table
> dbdocs update for item_template

- World/Updates/Rel21/Rel21_1_21_dbdocs_update_custom_texts.sql
custom texts - Notes and Description filled in
item_template - corrections made to 2 submodule tables (justification of
text)
> dbdocs update to custom_texts table

- World/Updates/Rel21/Rel21_1_23_more_dbdocs_updates.sql
Updates made in dbdocs table, subtables and fields.
> Update to dbdocs

- World/Updates/Rel21/Rel21_1_25_dbdocs_updates.sql
Updates to the dbdocs dbdocssubtables and dbdocsfields.
> dbdocs updates

- World/Updates/Rel21/Rel21_1_16_improved_trap_radius.sql
- World/Updates/Rel21/Rel21_1_26_quest_3022_level_fix.sql
- World/Updates/Rel21/Rel21_1_26_quest_level_fixes.sql
Added an entry clause to the update so it would work.
> Fix SQL code in R21_1_16 and fix quest levels

- World/Updates/Rel21/Rel21_2_2_npc_10578_gossip_fix.sql
> NPC 10578 (Bom`bay) gossip fix.

- World/Updates/Rel21/Rel21_2_3_npc_15213_event_ai_fix.sql
Add missing spells 9672, 11831, 12058 and 13339
> [EventAI]Add creature 15213 missing event ai

- World/Updates/Rel21/Rel21_4_2_mass_updates.sql
Many updates by many authors:
-- cala
-- cyberium
-- DDuarte
-- evil-at-wow
-- Grz3s
-- jeeron-- jpiolho
-- Kelzior
-- Killyana
-- Muehe
-- nekoi
-- neotmiren
-- Scotty0100
-- stfx
-- thetrueanimal
-- Tobschinski
-- Xfurry
-- zingzah
-- TrinityCore
-- UDB
-- YTDB
> Many, many updates

- World/Updates/Rel21/Rel21_5_3_BRD_Ring_Of_Law_fix.sql
Author: Tobschinsk
BRD Ring of Law fix
> BRD Ring of Law fix

- World/Updates/Rel21/Rel21_5_5_mass_updates_and_fixes.sql
Many, many updates.
This also includes many start up fixes.
Thanks to the following authors:
adellaci
cala
cooler-SAI
Grz3s
k59
Muehe
NeatElves
Tobschinski
xfurry
Zingzah
> Mass updates and fixes

- World/Updates/Rel21/Rel21_5_6_quest_1948.sql
https://www.getmangos.eu/issue.php?issueid=735
Since [this core commit](https://github.com/mangoszero/server/commit/2a71b6a08901f927f2699436f415df33bd7e3fc5) by @H0zen , the solution is easy.
> Correct trap radius for Items of Power quest

- World/Updates/Rel21/Rel21_7_2_quest_658_fix_.sql
The courier will now drop the quest loot.
> Quest 658 fix (quest loot drop)

- World/Updates/Rel21/Rel21_11_26_stratholme_fixes.sql
* NPC Ysida is now spawned on event start
* Her speeches are added
* Tuning of the timers
* Run failure is now handled
* Event is completable
* Reputation reward is added
* Special case when timer expires while fighting the Baron is handled
(based on commit https://github.com/cmangos/mangos-classic/commit/cf63af912c3e7d2891903854d1ef6eca64c835a1)
> Improved Baron in Stratholme

- World/Updates/Rel21/Rel21_11_36_Set_Demon_Portal_to_close_for_15_minutes.sql
Quest 5581 can finish the whole task at one Demon Portal.
Set Demon Portal to close for 15 minutes.
> Adjust_Demon_Portal_Time

- World/Updates/Rel21/Rel21_11_43_various_quest_fixes.sql
2 files were labelled Rel21_11_26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/60)
> File renamed due to having duplicate revsion

- World/Updates/Rel21/Rel21_11_44_Quest_27469.sql
Quest 27469 Friends on The Other Side
Implemented for Horde and Alliance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/61)
> Quest 27469 Friends on The Other Side

- World/Updates/Rel21/Rel21_11_45_Update_DBScript_Type.sql
- World/Updates/Rel21/Rel21_11_46_BRD_updates.sql
BRD Grimm Guzzler updates from cmangos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/62)
> BRD Grimm Guzzler updates from cmangos

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/64)
> Editing the README.md file with updated Linux procedure.

- InstallDatabases.sh
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/65)
> Adding silent mode to Linux setup script

- World/Updates/Rel21/Rel21_11_48_NPC 18253 gossip fix.sql
- Removed blank gossip
- Cleanup unused menu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/67)
> Archmage Leryda gossip fix

- World/Updates/Rel21/Rel21_11_50_Spotlight_spell_effect.sql
The creature used in the spotlight effect from the elune stone and
elders moonstone should not target or be targeted by players.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/68)
> Spotlight spell effect update

- World/Updates/Rel21/Rel21_11_51_Terenthis_Emote_Fix.sql
-Terenthis  was using "say" rather than using an emote when casting his
spell during the A Lost Master quest.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/69)
> Terenthis will now emote correctly

- World/Updates/Rel21/Rel21_11_75_Fix_Weapon_Damage.sql
- World/Updates/Rel21/Rel21_11_76_bootybay_gnomeregan_teleport_fix.sql
- World/Updates/Rel21/Rel21_11_77_Feast_of_Winter_Veil_part1.sql
Apostrophe fix for previous update (Rel21_11_75_Fix_Weapon_Damage.sql)
Naming fix for previous update (Rel21_11_75_bootybay_gnomeregan_teleport_fix.sql)
Feast of Winter Veil fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/89)
> Feast of Winter Veil

- World/Updates/Rel21/Rel21_11_79_Fix_Mailbox_Missing.sql
Fixed a mailbox missiong at the gate of the Valley of Honor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/92)
> fix mailbox missing

- World/Updates/Rel21/Rel21_11_79_Fix_Mailbox_Missing.sql
fix syntax error in line 7 and 17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mangoszero/database/94)
> fix syntax error
